### ISSUE TITLE
Glowstone 2 inconsistent name

### ISSUE THREAD

**Issue by iRewiewer** [Nibaru/Compressed-Fabric#2]
![image](https://user-images.githubusercontent.com/21245479/125356208-9162a180-e36e-11eb-839f-4efeb255f24d.png)

Just a lil name error, for consistency

**Comment by puggan** [comment]
here:
https://github.com/Nibaru/Compressed-Fabric/blob/51d9607367c09c40f72aafe24da1781a047ca351/src/main/resources/assets/compressed/lang/en_us.json#L104
